### ISSUE TITLE
How to edit or delete a snippet?

### ISSUE THREAD

**Issue by achiinto** [nikitaKunevich/vscode-snippet-creator#8]
Is there a way? or a place that stored the created snippets, which we can go to modify?

**Comment by ethan-dowler** [comment]
if you open the command palette, search for 'Preferences: Configure User Snippets'. it will then ask for which file extension you want to edit snippets for. just type in 'html', 'scss', 'javascript', etc. and you can edit your snippets in the corresponding json file.

Just a tip, the most useful edit is to add tab stops to the snippet using $1, $2, $3, etc.

**Comment by achiinto** [comment]
Thanks for the information. I will give it a try. Love the simplicity of the tool so far.

**Comment by achiinto** [comment]
Confirmed, that answered my question. Very useful tool indeed.
